#!/bin/bash
sudo apt update
apt install apache2
apt install mysql-server
apt install php libapache2-mod-php php-mysql
systemctl restart apache2

mysql <wishlist.sql
cp index.php /var/www/html
cp wishlist.php /var/www/html

exit
=======
